version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakusr
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    restart: always
    command: start-dev
    environment:
      DB: postgres
      DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      DB_USERNAME: keycloakusr
      DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - keycloak-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - keycloak
    networks:
      - keycloak-net

volumes:
  postgres_data:

networks:
  keycloak-net:
