services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakusr
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: keycloakusr
      KC_DB_PASSWORD: secret
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_PROXY: "edge"
      KC_HOSTNAME: "hylastixproject.ddns.net"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTPS_REQUIRED: "external"
    depends_on:
      - postgres
    networks:
      - keycloak-net
    ports:
      - "8080:8080"


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /opt/app/docker/page:/usr/share/nginx/html:ro
      - /opt/app/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/app/cert:/etc/nginx/cert:ro
    networks:
      - keycloak-net
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:

networks:
  keycloak-net:
    name: keycloak-net