- name: Configure Azure virtual machine
  hosts: azure_virtual_machine
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: true
        cache_valid_time: 300

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Create app directory
      file:
        path: /opt/app
        state: directory

    - name: Copy docker-compose.yaml
      copy:
        src: /Users/milosacimovic/Desktop/Test-task/hylastix-task-new/docker/docker-compose.yaml
        dest: /opt/app/docker-compose.yaml

    - name: Copy nginx configuration
      copy:
        src: /Users/milosacimovic/Desktop/Test-task/hylastix-task-new/docker/nginx.conf
        dest: /opt/app/nginx.conf

    - name: Create folder for static page
      file:
        path: /opt/app/page
        state: directory
        mode: '0755'

    - name: Copy static page
      copy:
        src: /Users/milosacimovic/Desktop/Test-task/hylastix-task-new/docker/page/testpage.html
        dest: /opt/app/page/testpage.html
        mode: '0644'

    - name: Run containers
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present